package com.old.silence.config.center.domain.model;


import com.baomidou.mybatisplus.annotation.TableField;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;


public class ConfigCyberarkInfo extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * cyberark对象
     */
    private String cyberarkObject;

    /**
     * 加密后的值
     */
    private String encryptedValue;

    /**
     * 所属组件编码
     */
    private String componentCode;

    private String safe;

    private String folder;

    /**
     * 描述
     */
    private String description;

    /**
     * 是否启用
     */
    @TableField("is_enabled")
    private Boolean enabled;

    public String getCyberarkObject() {
        return cyberarkObject;
    }

    public void setCyberarkObject(String cyberarkObject) {
        this.cyberarkObject = cyberarkObject;
    }

    public String getEncryptedValue() {
        return encryptedValue;
    }

    public void setEncryptedValue(String encryptedValue) {
        this.encryptedValue = encryptedValue;
    }

    public String getComponentCode() {
        return componentCode;
    }

    public void setComponentCode(String componentCode) {
        this.componentCode = componentCode;
    }

    public String getSafe() {
        return safe;
    }

    public void setSafe(String safe) {
        this.safe = safe;
    }

    public String getFolder() {
        return folder;
    }

    public void setFolder(String folder) {
        this.folder = folder;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}